"""Keep the post-impact prospective chain alive.

Checks every recorded waiting launcher under `ops/prospective_live/`, respawns
dead waiting processes whose frozen run time is still in the future, and emits
plus spawns the next weekday session whenever fewer than two future sessions
are covered. All spawned work is zero-order by construction; this keeper only
re-issues commands recorded in launcher.json files or generated by the chain
emit subcommand.

Usage:
  keep_post_impact_chain.py --report          # JSON status only
  keep_post_impact_chain.py --repair          # respawn + extend, then report
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from scripts.run_post_impact_chain_session_cycle import next_weekday
from stock_v2.kiwoom_minute import KST

OPS_ROOT = ROOT / "ops/prospective_live"
CHAIN_CONFIG_PATTERN = re.compile(
    r"post_impact_(?:chain_session|next_session_shadow)_(\d{8})\.json$"
)
MINIMUM_FUTURE_SESSIONS = 2


def _now() -> pd.Timestamp:
    return pd.Timestamp.now(tz=KST)


def _pid_running(pid: int, command_fragment: str) -> bool:
    try:
        output = subprocess.run(
            ["ps", "-p", str(pid), "-o", "command="],
            check=False, capture_output=True, text=True,
        ).stdout.strip()
    except OSError:
        return False
    return bool(output) and command_fragment in output


def _load_launchers() -> list[dict[str, Any]]:
    launchers = []
    for path in sorted(OPS_ROOT.glob("*/launcher.json")):
        record = json.loads(path.read_text(encoding="utf-8"))
        record["_path"] = path
        launchers.append(record)
    return launchers


def _launcher_run_at(record: dict[str, Any]) -> pd.Timestamp | None:
    if record.get("run_at_kst"):
        return pd.Timestamp(record["run_at_kst"]).tz_convert(KST)
    config_rel = record.get("config")
    command = [str(part) for part in record.get("command") or []]
    for index, part in enumerate(command):
        if part == "--config" and index + 1 < len(command):
            config_rel = command[index + 1]
    if config_rel is None:
        return None
    config_path = ROOT / str(config_rel)
    if not config_path.is_file():
        return None
    config = json.loads(config_path.read_text(encoding="utf-8"))
    run_at = config.get("run_at_kst")
    if not run_at:
        return None
    return pd.Timestamp(run_at).tz_convert(KST)


def _spawn(record: dict[str, Any]) -> int:
    command = [str(part) for part in record["command"]]
    session_tag = record["_path"].parent.name
    launch_log = ROOT / "logs" / f"chain_keeper_spawn_{session_tag}.log"
    launch_log.parent.mkdir(parents=True, exist_ok=True)
    with launch_log.open("a", encoding="utf-8") as handle:
        handle.write(f"# respawned at {_now().isoformat()}\n")
        handle.flush()
        process = subprocess.Popen(
            command, cwd=ROOT, stdout=handle, stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    return process.pid


def _update_launcher(record: dict[str, Any], pid: int) -> None:
    path = record.pop("_path")
    record["pid"] = pid
    record["respawned_at_kst"] = _now().isoformat()
    record["respawned_by"] = "scripts/keep_post_impact_chain.py"
    path.write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    record["_path"] = path


def check_waiting_processes(repair: bool) -> list[dict[str, Any]]:
    results = []
    for record in _load_launchers():
        command = [str(part) for part in record.get("command") or []]
        fragment = next(
            (part for part in command if part.startswith("scripts/")), ""
        )
        run_at = _launcher_run_at(record)
        pid = int(record.get("pid") or 0)
        running = _pid_running(pid, fragment) if pid else False
        entry = {
            "launcher": str(record["_path"].relative_to(ROOT)),
            "pid": pid,
            "running": running,
            "run_at_kst": run_at.isoformat() if run_at is not None else None,
        }
        if run_at is None:
            entry["status"] = (
                "running_no_schedule" if running else "inactive"
            )
        elif run_at <= _now():
            entry["status"] = "executing" if running else "completed_or_stale"
        elif running:
            entry["status"] = "waiting"
        elif not record.get("command"):
            entry["status"] = "dead_no_command"
        elif repair:
            new_pid = _spawn(record)
            _update_launcher(record, new_pid)
            entry["status"] = "respawned"
            entry["pid"] = new_pid
        else:
            entry["status"] = "dead_waiting_process"
        results.append(entry)
    return results


def covered_sessions() -> list[str]:
    sessions = set()
    for path in (ROOT / "configs").iterdir():
        match = CHAIN_CONFIG_PATTERN.search(path.name)
        if match:
            raw = match.group(1)
            sessions.add(f"{raw[:4]}-{raw[4:6]}-{raw[6:]}")
    return sorted(sessions)


def latest_d_plus_one_config() -> Path:
    candidates = sorted(
        (ROOT / "configs").glob("post_impact_d_plus_one_*.json")
    )
    if not candidates:
        raise FileNotFoundError("no d-plus-one config exists")
    return candidates[-1]


def extend_coverage(repair: bool) -> list[dict[str, Any]]:
    actions = []
    sessions = covered_sessions()
    if not sessions:
        raise RuntimeError("no chain session configs found")
    today = str(_now().date())
    future = [session for session in sessions if session >= today]
    while len(future) < MINIMUM_FUTURE_SESSIONS:
        context = sessions[-1]
        target = next_weekday(context)
        action = {"emit_target": target, "context": context}
        if repair:
            emit = subprocess.run(
                [
                    str(ROOT / ".venv-mps-max/bin/python"),
                    "scripts/run_post_impact_chain_session_cycle.py",
                    "emit",
                    "--target-session", target,
                    "--context-session", context,
                    "--previous-d-plus-one",
                    str(latest_d_plus_one_config().relative_to(ROOT)),
                ],
                cwd=ROOT, check=False, capture_output=True, text=True,
            )
            action["emit_returncode"] = emit.returncode
            if emit.returncode != 0:
                action["emit_output"] = emit.stdout[-2000:] + emit.stderr[-2000:]
                actions.append(action)
                break
            emitted = json.loads(emit.stdout)
            compact = target.replace("-", "")
            d1_run = str(emitted["d_plus_one_run_date"]).replace("-", "")
            specs = [
                (
                    f"chain_session_{compact}",
                    "post_impact_chain_session_zero_order_cycle",
                    [
                        ".venv-mps-max/bin/python",
                        "scripts/run_post_impact_chain_session_cycle.py",
                        "run",
                        "--config", emitted["chain_cycle_config"],
                        "--event-log",
                        f"ops/prospective_live/chain_session_{compact}/events.jsonl",
                        "--phase-log",
                        f"logs/post_impact_chain_session_phases_{compact}.log",
                        "--lock-file",
                        f"ops/prospective_live/chain_session_{compact}/cycle.lock",
                    ],
                ),
                (
                    f"d_plus_one_{d1_run}",
                    "post_impact_d_plus_one_zero_order_cycle",
                    [
                        ".venv-mps-max/bin/python",
                        "scripts/run_post_impact_d_plus_one_cycle.py",
                        "--config", emitted["d_plus_one_config"],
                        "--event-log",
                        f"ops/prospective_live/d_plus_one_{d1_run}/events.jsonl",
                        "--phase-log",
                        f"logs/post_impact_d_plus_one_phases_{d1_run}.log",
                        "--lock-file",
                        f"ops/prospective_live/d_plus_one_{d1_run}/cycle.lock",
                    ],
                ),
            ]
            spawned = []
            for tag, role, command in specs:
                launcher_path = OPS_ROOT / tag / "launcher.json"
                launcher_path.parent.mkdir(parents=True, exist_ok=True)
                record = {
                    "broker_order_calls_allowed": False,
                    "command": command,
                    "launched_by": "scripts/keep_post_impact_chain.py",
                    "launched_at_kst": _now().isoformat(),
                    "live_orders_allowed": False,
                    "role": role,
                    "_path": launcher_path,
                }
                pid = _spawn(record)
                _update_launcher(record, pid)
                spawned.append({"launcher": tag, "pid": pid})
            action["spawned"] = spawned
        actions.append(action)
        sessions.append(target)
        future.append(target)
    return actions


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--report", action="store_true")
    mode.add_argument("--repair", action="store_true")
    args = parser.parse_args()
    repair = bool(args.repair)
    report = {
        "checked_at_kst": _now().isoformat(),
        "mode": "repair" if repair else "report",
        "waiting_processes": check_waiting_processes(repair),
        "coverage_actions": extend_coverage(repair),
        "covered_sessions": covered_sessions(),
        "live_orders_allowed": False,
        "broker_order_calls_executed": 0,
    }
    problems = [
        entry for entry in report["waiting_processes"]
        if entry["status"] in {"dead_waiting_process", "dead_no_command"}
    ] + [
        action for action in report["coverage_actions"]
        if not repair or action.get("emit_returncode") not in (None, 0)
    ]
    report["needs_attention"] = bool(problems)
    print(json.dumps(report, indent=2, sort_keys=True))
    return 1 if report["needs_attention"] else 0


if __name__ == "__main__":
    sys.exit(main())
